# Generated by Django 5.0.3 on 2024-12-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasiKOS_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penilaian',
        ),
    ]
