# Generated by Django 5.0 on 2024-12-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasiKOS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kos',
            name='Jumlah_Kamar',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kos',
            name='jenis',
            field=models.CharField(default='Laki-Laki', max_length=255),
        ),
    ]
