# Generated by Django 5.0 on 2024-12-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasiKOS_app', '0002_kos_jumlah_kamar_kos_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kos',
            name='Jumlah_Kamar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
