# Generated by Django 5.0.3 on 2024-12-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasiKOS_app', '0003_penilaian'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteria',
            name='keterangan',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
